image: steveblackburn/comp1110-2020-s2-gitlab-ci:0.1.1

stages:
  - integrity
  - compliance
  - build
  - test

before_script:
  - export PATH_TO_FX=/usr/share/openjfx/lib
  - export JAVAFX_OPTIONS="--module-path $PATH_TO_FX"
  - export CP=src:/ass1/comp1110-ass1-tests.jar:/ass1/hamcrest-core-1.3.jar:/ass1/junit-4.12.jar

integrity:
  tags:
    - comp1110
  stage: integrity
  script:
    - python3 /validate.py --integrity comp1110-ass1

admin:
  tags:
    - comp1110
  stage: compliance
  script:
    - python3 /validate.py --schema https://cs.anu.edu.au/courses/comp1110/schemas/statement-of-originality.json ./originality.yml

build:
  tags:
    - comp1110
  stage: build
  script:
    - javac -encoding utf-8 $JAVAFX_OPTIONS -cp $CP src/comp1110/ass1/*.java
  artifacts:
    paths:
      - src/comp1110/ass1/*.class

task1:
  tags:
    - comp1110
  stage: test
  script:
    - java $JAVAFX_OPTIONS -cp $CP org.junit.runner.JUnitCore comp1110.ass1.PlacementToPositionTest
  allow_failure: true

task2:
  tags:
    - comp1110
  stage: test
  script:
    - java $JAVAFX_OPTIONS -cp $CP org.junit.runner.JUnitCore comp1110.ass1.DirectionFromCharTest
    - java $JAVAFX_OPTIONS -cp $CP org.junit.runner.JUnitCore comp1110.ass1.DirectionToCharTest
    - java $JAVAFX_OPTIONS -cp $CP org.junit.runner.JUnitCore comp1110.ass1.PlacementToOrientationTest
  allow_failure: true

task3:
  tags:
    - comp1110
  stage: test
  script:
    - java $JAVAFX_OPTIONS -cp $CP org.junit.runner.JUnitCore comp1110.ass1.GetOppositeTest
  allow_failure: true

task4:
  tags:
    - comp1110
  stage: test
  script:
    - java $JAVAFX_OPTIONS -cp $CP org.junit.runner.JUnitCore comp1110.ass1.IsBoardStateValidTest
  allow_failure: true

task5:
  tags:
    - comp1110
  stage: test
  script:
    - java $JAVAFX_OPTIONS -cp $CP org.junit.runner.JUnitCore comp1110.ass1.NewObjectiveTest
  allow_failure: true

task6:
  tags:
    - comp1110
  stage: test
  script:
    - java $JAVAFX_OPTIONS -cp $CP org.junit.runner.JUnitCore comp1110.ass1.GetNextPositionTest
  allow_failure: true

task7:
  tags:
    - comp1110
  stage: test
  script:
    - java $JAVAFX_OPTIONS -cp $CP org.junit.runner.JUnitCore comp1110.ass1.AdjacencyDirectionTest
  allow_failure: true
  
task8:
  tags:
    - comp1110
  stage: test
  script:
    - java $JAVAFX_OPTIONS -cp $CP org.junit.runner.JUnitCore comp1110.ass1.CanMoveTileTest
  allow_failure: true

task9:
  tags:
    - comp1110
  stage: test
  script:
    - java $JAVAFX_OPTIONS -cp $CP org.junit.runner.JUnitCore comp1110.ass1.IsTileMovementValidTest
  allow_failure: true
  
task10:
  tags:
    - comp1110
  stage: test
  script:
    - java $JAVAFX_OPTIONS -cp $CP org.junit.runner.JUnitCore comp1110.ass1.CanTransitTest
  allow_failure: true

task11:
  tags:
    - comp1110
  stage: test
  script:
    - java $JAVAFX_OPTIONS -cp $CP org.junit.runner.JUnitCore comp1110.ass1.GetPegPathStepTest
  allow_failure: true
  
task12:
  tags:
    - comp1110
  stage: test
  script:
    - java $JAVAFX_OPTIONS -cp $CP org.junit.runner.JUnitCore comp1110.ass1.GetPegPathToDestinationTest
  allow_failure: true
  
task13:
  tags:
    - comp1110
  stage: test
  script:
    - java $JAVAFX_OPTIONS -cp $CP org.junit.runner.JUnitCore comp1110.ass1.GetSolutionsTest
  allow_failure: true
  
## Local Variables:
## mode: yaml
## End:
